name: "Run JavaScript Action"
on:
  push:
    branches:
      - master
      - 'releases/*'   # only run in release distribution branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: wesleytodd/javascript-action@master
      with:
        milliseconds: 1000
